name: sg_easy_hire
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  amplify_flutter: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_storage_s3: ^2.7.0
  amplify_api: ^2.0.0
  amplify_push_notifications_pinpoint: ^2.0.0
  bloc: ^9.0.1
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^17.0.0
  google_fonts: ^6.3.3
  intl: ^0.20.2
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  dropdown_button2: ^2.3.9
  flutter_styled_toast: ^2.3.0
  nanoid: ^1.0.0
  freezed_annotation: ^2.4.4
  freezed: ^2.5.0
  pinput: ^6.0.1
  flutter_screenutil: ^5.9.3
  amplify_datastore: ^2.8.0
  material_symbols_icons: ^4.2892.0
  cached_network_image: ^3.4.1

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  

flutter:
  generate: true
  uses-material-design: true
  
